package br.com.study.crud.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "pessoa")
public class Pessoa {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String pessoaId;

    @DynamoDBAttribute
    private String sobrenome;

    @DynamoDBAttribute
    private String nome;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private Departamento departmento;

}
